### ISSUE TITLE
Is the README example correct for inputs that aren't a multiple of VF32_WIDTH?

### ISSUE THREAD

**Issue by oconnor663** [jackmott/simdeez#2]
It looks like it's loading vectors from each input slice without checking whether there are enough elements remaining in the slice. But maybe I missed some detail about how this gets handled?

**Comment by jackmott** [comment]
you are correct, the example assumes an evenly divisible input length.  For now you have to just handle this manually, I've been thinking on utility functions or maybe using iterators to make that easier. If you have ideas let me know!
