### ISSUE TITLE
safe conversion between different wrappers over the same underlying simd type (e.g. __m256i)

### ISSUE THREAD

**Issue by eoxcross** [jackmott/simdeez#23]
`packed_simd` exposes an `into_bits()` trait method that safely converts between types where it makes sense to do so based on the underlying bit-patterns. For example, one can convert between `u32x4` and `u64x2` safely.

Is there a way to do this in `simdeez` at the moment?

**Comment by jackmott** [comment]
No, you can use transmute, which is unsafe but so is simdeez. Simdeez doesn't attempt to be a safe wrapper over simd.
