### ISSUE TITLE
Version 1.0.1 broke semver guarantees

### ISSUE THREAD

**Issue by caelunshun** [jackmott/simdeez#30]
The release of version 1.0.1 broke semver compatibility guidelines by removing the `overloads` module:

https://github.com/jackmott/simdeez/commit/71f6edb1ac89cc4a233e62291f6920c43b6134fb#diff-b4aea3e418ccdb71239b96952d9cddb6L138

This subsequently broke my build as `simdnoise` depends on `simdeez`, and `simdnoise` has not yet been upgraded on crates.io to account for the breaking change.

**Comment by jackmott** [comment]
sorry about that, fix incoming

**Comment by jackmott** [comment]
ok grab latest rust-simd-noise and let me know if all is well

**Comment by caelunshun** [comment]
It's fixed now, thanks for the quick response!
