### ISSUE TITLE
simd_runtime_generate! broken in 1.01

### ISSUE THREAD

**Issue by ronniec95** [jackmott/simdeez#32]
Using that macro currently fails with

```
cannot find type `Avx` in this scoperustc(E0412)
avx2.rs(8, 1): similarly named struct `Avx2` defined here
lib.rs(111, 5): a struct with a similar name exists
```

Missing a few use and target_feature statements I noticed - I can submit a PR
Also the compile_time macro doesn't generate avx  - missing cfg()

**Comment by jackmott** [comment]
Apologies for that, give it a try in 1.0.2, if all is well you can go ahead and close.,

**Comment by ronniec95** [comment]
Great thank you
