### ISSUE TITLE
stdsimd is now on stable

### ISSUE THREAD

**Issue by sanxiyn** [jackmott/simdeez#9]
As I understand, stdsimd has been stable since [1.27](https://blog.rust-lang.org/2018/06/21/Rust-1.27.html), so "SIMDeez builds on stable rust now, stdsimd does not" in README should be updated.

**Comment by jackmott** [comment]
That is just the raw intrinsics, which all of these library use ultimately.
stdsimd has been renamed: https://github.com/rust-lang-nursery/packed_simd
and isn't in stable yet.

I'll change the name though in my readme.
